name: arxiv-trends
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scikit-learn
  - plotly
  - matplotlib
  - numpy
  - seaborn
  - jupyterlab
  - pandas
  - umap-learn
  - hdbscan
  - matplotlib-venn
  - langdetect
